=head1 RANGE SEARCHING

The C<--range-start> and C<--range-stop> options let you specify ranges of
lines to search within each file.

Say you had the following file, called F<testfile>:

    # This function calls print on "foo".
    sub foo {
        print 'foo';
    }
    my $print = 1;
    sub bar {
        print 'bar';
    }
    my $task = 'print';

Calling C<ack print> will give us five matches:

    $ ack print testfile
    # This function calls print on "foo".
        print 'foo';
    my $print = 1;
        print 'bar';
    my $task = 'print';

What if we only want to search for C<print> within the subroutines?  We can
specify ranges of lines that we want ack to search.  The range starts with
any line that matches the pattern C<^sub \w+>, and stops with any line that
matches C<^}>.

    $ ack --range-start='^sub \w+' --range-stop='^}' print testfile
        print 'foo';
        print 'bar';

Note that ack searched two ranges of lines.  The listing below shows which
lines were in a range and which were out of the range.

    Out # This function calls print on "foo".
    In  sub foo {
    In      print 'foo';
    In  }
    Out my $print = 1;
    In  sub bar {
    In      print 'bar';
    In  }
    Out my $task = 'print';

You don't have to specify both C<--range-start> and C<--range-stop>.  IF
C<--range-start> is omitted, then the range runs from the first line in the
file unitl the first line that matches C<--range-stop>.  Similarly, if
C<--range-stop> is omitted, the range runs from the first line matching
C<--range-start> to the end of the file.

It's possible for a range to start and stop on the same line.  For example

    --range-start='<title>' --range-end='</title>'

would match this line as both the start and end of the range, making a
one-line range.

    <title>Page title</title>

Again, ranges only affect where matches are looked for.  Everything else in
ack works the same way.  Using C<-c> option with a range will give a count
of all the matches that appear within those ranges.  The C<-l> shows those
files that have a match within a range, and the C<-L> option shows files
that do not have a match within a range.

Specifying a range to search does not affect how matches are displayed.
The context for a match will still be the same, and

Using the context options work the same way, and will show context lines
for matches even if the context lines fall outside the range.
